/* Author: huma23, github.com/huma23
 * 
 * This file is part of the Wahlzeit photo rating application.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public
 * License along with this program. If not, see
 * <http://www.gnu.org/licenses/>.
 */
package org.wahlzeit.model.coordinate;

import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.HashMap;
import java.util.Map;

import org.wahlzeit.utils.Assertions;

/**
 * A CartesianCoordinate represents one coordinate in a cartesian space
 */
public class CartesianCoordinate extends AbstractCoordinate{

	private final double x;
	private final double y;
	private final double z;
	private final static Map<Integer, CartesianCoordinate> SHARED_COORDINATES = new HashMap<>();

	/**
	 * Checks if the current Cartesian value already exists and returns it.
	 * Otherwise it creates a new value and returns it.
	 * @param x
	 * @param y
	 * @param z
	 * @return
	 */
	public static CartesianCoordinate createCartesianCoordinate(double x, double y, double z) {
		CartesianCoordinate tempCartesianCoordinate = new CartesianCoordinate(x, y, z);
		return createCoordinate(SHARED_COORDINATES, tempCartesianCoordinate);
	}
	
	/**
	 * Constructor for creating an instance of a CartesianCoordinate
	 * @param x
	 * @param y
	 * @param z
	 */
	private CartesianCoordinate(double x, double y, double z) {
		this.x = x;
		this.y = y;
		this.z = z;
		assertClassInvariants();
	}
	
	/**
	 * Compares the values of each axis and returns true if equal.
	 * @param coordinate
	 * @return
	 */
	@Override
	protected boolean doIsEqual(Coordinate coordinate) {
		
		return this.hashCode() == coordinate.hashCode();
	}
	
	/**
	 * Generated by eclipse
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		long temp;
		temp = Double.doubleToLongBits(x);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		temp = Double.doubleToLongBits(y);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		temp = Double.doubleToLongBits(z);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		return result;
	}
	
	/**
	 * Returns a string with the format: "(x / y / z)"
	 * The  values are represented with two decimals.
	 */
	@Override
	public String toString() {
		
		DecimalFormatSymbols symbol = new DecimalFormatSymbols();
		symbol.setDecimalSeparator(',');
		symbol.setGroupingSeparator('.');
		DecimalFormat format = new DecimalFormat("#0.00", symbol);
		
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.append("(x / y / z): (");
		stringBuilder.append(format.format(x));
		stringBuilder.append(" / ");
		stringBuilder.append(format.format(y));
		stringBuilder.append(" / ");
		stringBuilder.append(format.format(z));
		stringBuilder.append(")");
		return stringBuilder.toString();
	}

	/**
	 * Returns the current object, because it is already an instance of a CartesianCoordinate
	 */
	@Override
	protected CartesianCoordinate doAsCartesianCoordinate() {	
		return this;
	}

	/**
	 * Converts this CartesianCoordinate to a SquericCoordinate.
	 */
	@Override
	protected SphericCoordinate doAsSphericCoordinate() {
		
		double radius = Math.sqrt(Math.pow(this.x, 2) + Math.pow(this.y, 2) + Math.pow(this.z, 2));
		double latitude = Math.toDegrees(Math.atan(this.y / this.x));
		double longitude = Math.toDegrees(Math.atan(Math.sqrt((Math.pow(this.x, 2)) + Math.pow(this.y, 2)) / this.z));
		
		return SphericCoordinate.createSphericCoordinate(latitude, longitude, radius);
	}
	
	@Override
	protected double doGetCartesianDistance(Coordinate coordinate) {
		
		CartesianCoordinate compareCoordinate = coordinate.asCartesianCoordinate();

		double squarresSum = Math.pow(compareCoordinate.getX() - this.getX(), 2) 
				+ Math.pow(compareCoordinate.getY() - this.getY(), 2) 
				+ Math.pow(compareCoordinate.getZ() - this.getZ(), 2); 
		double distance = Math.sqrt(squarresSum);
		
		return distance;
	}
	
	@Override
	protected double doGetSphericDistance(Coordinate coordinate) {
		
		return this.asSphericCoordinate().doGetSphericDistance(coordinate);
	}
	
	@Override
	public void assertClassInvariants() {
		
		//There are only double values in this class so they need to be checked
		Assertions.assertValidDoubleValue("X", x);
		Assertions.assertValidDoubleValue("Y", y);
		Assertions.assertValidDoubleValue("Z", z);
	}

	/*
	 * Getters for this class 
	 */
	public double getX() {
		return x;
	}

	public double getY() {
		return y;
	}

	public double getZ() {
		return z;
	}
}
