/* Author: huma23, github.com/huma23
 * 
 * This file is part of the Wahlzeit photo rating application.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public
 * License along with this program. If not, see
 * <http://www.gnu.org/licenses/>.
 */
package org.wahlzeit.model.coordinate;

import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;

/**
 * A SphericCoordinate represents one coordinate in a spheric space
 */
public class SphericCoordinate extends AbstractCoordinate {
	
	public static final double EARTH_RADIUS = 6378.0;
	
	private double latitude;
	private double longitude;
	private double radius;

	/**
	 * Constructor for creating an instance of a SphericCoordinate
	 * @param latitude
	 * @param longitude
	 * @param radius
	 */
	public SphericCoordinate(double latitude, double longitude, double radius) {
		this.latitude = latitude;
		this.longitude = longitude;
		this.radius = radius;
	}
	
	/**
	 * Constructor for creating an instance of a SphericCoordinate with EARTH_RADIUS 
	 * as default for parameter radius
	 * @param latitude
	 * @param longitude
	 */
	public SphericCoordinate(double latitude, double longitude) {
		this.latitude = latitude;
		this.longitude = longitude;
		this.radius = EARTH_RADIUS;
	}

	/**
	 * Converts this SphericCoordinate to a CartesianCoordinate.
	 */
	@Override
	public CartesianCoordinate asCartesianCoordinate() {
		
		double radiantPhi = Math.toRadians(this.latitude);
		double radiantLambda = Math.toRadians(this.longitude);
		
		double x = this.radius * Math.sin(radiantLambda) * Math.cos(radiantPhi);
		double y = this.radius * Math.sin(radiantLambda) * Math.sin(radiantPhi);
		double z = this.radius * Math.cos(radiantLambda);
		
		return new CartesianCoordinate(x, y, z);
	}

	/**
	 * Returns the current object, because it is already an instance of a SquericCoordinate
	 */
	@Override
	public SphericCoordinate asSphericCoordinate() {	
		return this;
	}

	/**
	 * Compares the values of latitude, longitude and radius. Returns true if equal.
	 * @param coordinate
	 * @return
	 */
	@Override
	public boolean isEqual(Coordinate coordinate) {
		
		assertCoordinateIsNotNull(coordinate);
		
		return Math.abs(this.longitude - coordinate.asSphericCoordinate().longitude) <= EPSILON 
				&& Math.abs(this.latitude - coordinate.asSphericCoordinate().latitude) <= EPSILON 
				&& Math.abs(this.radius - coordinate.asSphericCoordinate().radius) <= EPSILON;
	}

	/**
	 * Generated by eclipse
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		long temp;
		temp = Double.doubleToLongBits(latitude);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		temp = Double.doubleToLongBits(longitude);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		temp = Double.doubleToLongBits(radius);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		return result;
	}
	
	/**
	 * Returns a string with the format: "(latitude / longitude / radius)"
	 * The  values are represented with two decimals.
	 */
	@Override
	public String toString() {
		DecimalFormatSymbols symbol = new DecimalFormatSymbols();
		symbol.setDecimalSeparator(',');
		symbol.setGroupingSeparator('.');
		DecimalFormat format = new DecimalFormat("#0.00", symbol);
		
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.append("(latitude / longitude / radius): (");
		stringBuilder.append(format.format(latitude));
		stringBuilder.append(" / ");
		stringBuilder.append(format.format(longitude));
		stringBuilder.append(" / ");
		stringBuilder.append(format.format(radius));
		stringBuilder.append(")");
		return stringBuilder.toString();
	}

	/*
	 * Getters
	 */
	public double getLatitude() {
		return latitude;
	}

	public double getLongitude() {
		return longitude;
	}

	public double getRadius() {
		return radius;
	}
}
